[2022-03-24 11:13:33,773] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.test.iowa.general_store_facts manual__2022-03-23T19:14:12.667416+00:00 [queued]>
[2022-03-24 11:13:33,780] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.test.iowa.general_store_facts manual__2022-03-23T19:14:12.667416+00:00 [queued]>
[2022-03-24 11:13:33,780] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 11:13:33,781] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-24 11:13:33,781] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 11:13:33,789] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): test.iowa.general_store_facts> on 2022-03-23 19:14:12.667416+00:00
[2022-03-24 11:13:33,791] {standard_task_runner.py:52} INFO - Started process 419 to run task
[2022-03-24 11:13:33,794] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'test.iowa.general_store_facts', 'manual__2022-03-23T19:14:12.667416+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/transform_dags.py', '--cfg-path', '/tmp/tmpv7doduvi', '--error-file', '/tmp/tmpkpest30_']
[2022-03-24 11:13:33,794] {standard_task_runner.py:77} INFO - Job 128: Subtask test.iowa.general_store_facts
[2022-03-24 11:13:33,845] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.test.iowa.general_store_facts manual__2022-03-23T19:14:12.667416+00:00 [running]> on host a91ac75a8f43
[2022-03-24 11:13:33,894] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=test.iowa.general_store_facts
AIRFLOW_CTX_EXECUTION_DATE=2022-03-23T19:14:12.667416+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-23T19:14:12.667416+00:00
[2022-03-24 11:13:33,894] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-24 11:13:33,895] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            cd /opt/iowa/dbt/iowa &&\n            dbt --no-write-json test --target dev --models general_store_facts\n            ']
[2022-03-24 11:13:33,900] {subprocess.py:85} INFO - Output:
[2022-03-24 11:13:37,072] {subprocess.py:89} INFO - 11:13:37  Running with dbt=1.0.4
[2022-03-24 11:13:37,110] {subprocess.py:89} INFO - 11:13:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 188 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
[2022-03-24 11:13:37,112] {subprocess.py:89} INFO - 11:13:37
[2022-03-24 11:13:37,112] {subprocess.py:89} INFO - 11:13:37  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-03-24 11:13:38,787] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-24 11:13:38,811] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=test.iowa.general_store_facts, execution_date=20220323T191412, start_date=20220324T111333, end_date=20220324T111338
[2022-03-24 11:13:38,826] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-24 11:13:38,862] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
