[2022-03-21 23:19:38,584] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.trigger_dependent_dag scheduled__2012-01-01T00:00:00+00:00 [queued]>
[2022-03-21 23:19:38,591] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.trigger_dependent_dag scheduled__2012-01-01T00:00:00+00:00 [queued]>
[2022-03-21 23:19:38,591] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:19:38,591] {taskinstance.py:1244} INFO - Starting attempt 4 of 5
[2022-03-21 23:19:38,591] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:19:38,599] {taskinstance.py:1264} INFO - Executing <Task(TriggerDagRunOperator): trigger_dependent_dag> on 2012-01-01 00:00:00+00:00
[2022-03-21 23:19:38,603] {standard_task_runner.py:52} INFO - Started process 825 to run task
[2022-03-21 23:19:38,605] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'BQ_dag', 'trigger_dependent_dag', 'scheduled__2012-01-01T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpqhbtcmpy', '--error-file', '/tmp/tmpjt267xsz']
[2022-03-21 23:19:38,606] {standard_task_runner.py:77} INFO - Job 89: Subtask trigger_dependent_dag
[2022-03-21 23:19:38,653] {logging_mixin.py:109} INFO - Running <TaskInstance: BQ_dag.trigger_dependent_dag scheduled__2012-01-01T00:00:00+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 23:19:38,760] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BQ_dag
AIRFLOW_CTX_TASK_ID=trigger_dependent_dag
AIRFLOW_CTX_EXECUTION_DATE=2012-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-01-01T00:00:00+00:00
[2022-03-21 23:19:38,787] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/api/common/trigger_dag.py:84 DeprecationWarning: Calling `DAG.create_dagrun()` without an explicit data interval is deprecated
[2022-03-21 23:19:38,820] {trigger_dagrun.py:178} INFO - Waiting for EL_dag on 2022-03-21T23:19:38.761388+00:00 to become allowed state ['success'] ...
[2022-03-21 23:20:38,836] {trigger_dagrun.py:178} INFO - Waiting for EL_dag on 2022-03-21T23:19:38.761388+00:00 to become allowed state ['success'] ...
[2022-03-21 23:21:38,855] {trigger_dagrun.py:178} INFO - Waiting for EL_dag on 2022-03-21T23:19:38.761388+00:00 to become allowed state ['success'] ...
[2022-03-21 23:22:38,924] {trigger_dagrun.py:178} INFO - Waiting for EL_dag on 2022-03-21T23:19:38.761388+00:00 to become allowed state ['success'] ...
[2022-03-21 23:23:38,993] {trigger_dagrun.py:178} INFO - Waiting for EL_dag on 2022-03-21T23:19:38.761388+00:00 to become allowed state ['success'] ...
[2022-03-21 23:24:39,062] {trigger_dagrun.py:178} INFO - Waiting for EL_dag on 2022-03-21T23:19:38.761388+00:00 to become allowed state ['success'] ...
[2022-03-21 23:25:39,141] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/trigger_dagrun.py", line 189, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: EL_dag failed with failed states failed
[2022-03-21 23:25:39,145] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=BQ_dag, task_id=trigger_dependent_dag, execution_date=20120101T000000, start_date=20220321T231938, end_date=20220321T232539
[2022-03-21 23:25:39,154] {standard_task_runner.py:89} ERROR - Failed to execute job 89 for task trigger_dependent_dag
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/trigger_dagrun.py", line 189, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: EL_dag failed with failed states failed
[2022-03-21 23:25:39,174] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 23:25:39,199] {dagrun.py:627} WARNING - Failed to get task '<TaskInstance: BQ_dag.external_task_sensor scheduled__2012-01-01T00:00:00+00:00 [removed]>' for dag 'BQ_dag'. Marking it as removed.
[2022-03-21 23:25:39,208] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
