[2022-03-24 12:10:44,310] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.test.iowa.general_facts manual__2022-03-23T19:14:12.667416+00:00 [queued]>
[2022-03-24 12:10:44,316] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.test.iowa.general_facts manual__2022-03-23T19:14:12.667416+00:00 [queued]>
[2022-03-24 12:10:44,316] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 12:10:44,316] {taskinstance.py:1244} INFO - Starting attempt 3 of 3
[2022-03-24 12:10:44,316] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 12:10:44,323] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): test.iowa.general_facts> on 2022-03-23 19:14:12.667416+00:00
[2022-03-24 12:10:44,325] {standard_task_runner.py:52} INFO - Started process 767 to run task
[2022-03-24 12:10:44,328] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'test.iowa.general_facts', 'manual__2022-03-23T19:14:12.667416+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/transform_dags.py', '--cfg-path', '/tmp/tmpt0m7ja96', '--error-file', '/tmp/tmpawqg7jxn']
[2022-03-24 12:10:44,329] {standard_task_runner.py:77} INFO - Job 145: Subtask test.iowa.general_facts
[2022-03-24 12:10:44,376] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.test.iowa.general_facts manual__2022-03-23T19:14:12.667416+00:00 [running]> on host a91ac75a8f43
[2022-03-24 12:10:44,419] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=test.iowa.general_facts
AIRFLOW_CTX_EXECUTION_DATE=2022-03-23T19:14:12.667416+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-23T19:14:12.667416+00:00
[2022-03-24 12:10:44,420] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-24 12:10:44,421] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            cd /opt/iowa/dbt/iowa &&\n            dbt --no-write-json test --target dev --models general_facts\n            ']
[2022-03-24 12:10:44,425] {subprocess.py:85} INFO - Output:
[2022-03-24 12:10:47,737] {subprocess.py:89} INFO - 12:10:47  Running with dbt=1.0.4
[2022-03-24 12:10:47,785] {subprocess.py:89} INFO - 12:10:47  Found 5 models, 0 tests, 0 snapshots, 0 analyses, 188 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
[2022-03-24 12:10:47,787] {subprocess.py:89} INFO - 12:10:47
[2022-03-24 12:10:47,787] {subprocess.py:89} INFO - 12:10:47  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-03-24 12:10:49,523] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-24 12:10:49,546] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=test.iowa.general_facts, execution_date=20220323T191412, start_date=20220324T121044, end_date=20220324T121049
[2022-03-24 12:10:49,565] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-24 12:10:49,598] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
