[2022-03-18 21:41:58,061] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-03-18 21:41:58,067] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-03-18 21:41:58,067] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 21:41:58,067] {taskinstance.py:1244} INFO - Starting attempt 17 of 18
[2022-03-18 21:41:58,067] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 21:41:58,074] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): extract_task> on 2019-02-01 00:00:00+00:00
[2022-03-18 21:41:58,077] {standard_task_runner.py:52} INFO - Started process 1199 to run task
[2022-03-18 21:41:58,081] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'extract_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpl7u8wrsw', '--error-file', '/tmp/tmp4ij8e5ni']
[2022-03-18 21:41:58,082] {standard_task_runner.py:77} INFO - Job 28: Subtask extract_task
[2022-03-18 21:41:58,226] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.extract_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host d6b2ec1ac43c
[2022-03-18 21:41:58,301] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-18 21:41:58,334] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2022-03-18 21:42:00,717] {logging_mixin.py:109} INFO - the response is  200
[2022-03-18 21:42:00,718] {logging_mixin.py:109} INFO - here.........
[2022-03-18 21:42:00,791] {logging_mixin.py:109} INFO -    invoice_line_no  ...           store_location
0  INV-17291700004  ...                     None
1  INV-17291900021  ...                     None
2  INV-17286000008  ...  [-94.238806, 40.714826]
3  INV-17291600014  ...                     None
4  INV-17292900006  ...                     None

[5 rows x 24 columns]
[2022-03-18 21:42:00,807] {logging_mixin.py:109} INFO - Data saved..........
[2022-03-18 21:42:00,808] {python.py:175} INFO - Done. Returned value was: None
[2022-03-18 21:42:00,820] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=EL_dag, task_id=extract_task, execution_date=20190201T000000, start_date=20220318T214158, end_date=20220318T214200
[2022-03-18 21:42:00,864] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-18 21:42:00,890] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
