[2022-03-21 22:29:52,294] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor manual__2022-03-21T22:13:27.334303+00:00 [queued]>
[2022-03-21 22:29:52,299] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor manual__2022-03-21T22:13:27.334303+00:00 [queued]>
[2022-03-21 22:29:52,300] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:29:52,300] {taskinstance.py:1244} INFO - Starting attempt 2 of 4
[2022-03-21 22:29:52,300] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:29:52,307] {taskinstance.py:1264} INFO - Executing <Task(ExternalTaskSensor): external_task_sensor> on 2022-03-21 22:13:27.334303+00:00
[2022-03-21 22:29:52,310] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2022-03-21 22:29:52,313] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'BQ_dag', 'external_task_sensor', 'manual__2022-03-21T22:13:27.334303+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpfcb9e6fl', '--error-file', '/tmp/tmpqvdajrgw']
[2022-03-21 22:29:52,313] {standard_task_runner.py:77} INFO - Job 63: Subtask external_task_sensor
[2022-03-21 22:29:52,447] {logging_mixin.py:109} INFO - Running <TaskInstance: BQ_dag.external_task_sensor manual__2022-03-21T22:13:27.334303+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 22:29:52,493] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BQ_dag
AIRFLOW_CTX_TASK_ID=external_task_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-03-21T22:13:27.334303+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-21T22:13:27.334303+00:00
[2022-03-21 22:29:52,494] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:43:27.334303+00:00 ... 
[2022-03-21 22:30:52,564] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:43:27.334303+00:00 ... 
[2022-03-21 22:30:58,945] {local_task_job.py:211} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-03-21 22:30:58,946] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 295. PIDs of all processes in the group: [295]
[2022-03-21 22:30:58,947] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 295
[2022-03-21 22:30:58,947] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-21 22:30:58,973] {process_utils.py:70} INFO - Process psutil.Process(pid=295, status='terminated', exitcode=0, started='22:29:51') (295) terminated with exit code 0
